"""QUARANTINED LEGACY BUILDER — DO NOT RUN FOR PRODUCTION.

Superseded on 2026-07-21 by the verified final package and
``build_siegebreaker_final_package_a01.py``. This file uses the obsolete
grip-centered coordinate frame and is preserved only for historical diagnosis.

SM_DRW_SiegeBreaker_Hammer_A01 - DCC Blockout Generator

Purpose: Create a centered, scaled blockout mesh for the Siege Breaker
dwarven great hammer following the approved production package dimensions.

Authority:
  - Visual canon: VC-DRW-SiegeBreaker-Hammer-A01 (approved 2026-07-07)
  - Production package: docs/assets/props/SM_DRW_SiegeBreaker_Hammer_A01/PRODUCTION_PACKAGE.md
  - Dimensions from concept art specification

Dimensions (source authority):
  Overall length:    170 cm
  Head max width:    52 cm
  Head height:       38 cm
  Head depth:        32 cm
  Shaft length:      118 cm
  Grip wrap length:  42 cm
  Handle diameter:   5 cm
  Pommel length:     18 cm
  Pommel max width:  11 cm

Scale convention:
  1 Blender unit = 1 cm
  Origin: center of grip area (where hands would hold)
  Hammer points along +Z axis (head at top, pommel at bottom)

Component layout along Z axis:
  Head top:        +85 cm
  Head bottom:     +47 cm (38 cm head height)
  Shaft start:     -21 cm
  Grip zone:       -43 to -85 cm
  Pommel top:      -103 cm
  Pommel bottom:   -118 cm
  Total span:      170 cm (85 - (-85))

Generated by: Hermes (Aerathea Codex)
Date: 2026-07-07
"""

import math

# Blender API imports (run from Blender Text Scripting)
import bpy
import mathutils
from mathutils import Vector, Matrix

def clear_scene():
    """Clear all meshes from scene for clean blockout."""
    bpy.ops.object.select_all(action='SELECT')
    bpy.ops.object.delete()

def create_material(name, color):
    """Create a simple diffuse material for visual separation."""
    mat = bpy.data.materials.new(name=name)
    mat.diffuse_color = color
    mat.use_nodes = True
    return mat

def create_head():
    """
    Create the faceted stone hammer head.
    
    Dimensions: 52 cm W x 38 cm H x 32 cm D
    Position: Z = +47 to +85 (38 cm height)
    """
    bpy.ops.mesh.primitive_uv_sphere_add(
        radius=16,  # approximate half-depth of head
        segments=8,
        ring_count=6
    )
    head = bpy.context.active_object
    head.name = "Head_Blockout"
    
    # Scale to approximate the faceted stone shape
    # Width 52, Height 38, Depth 32
    head.scale = (26, 16, 19)  # half-dimensions
    head.location.z = 66  # center of 38cm head at Z=47..85
    
    bpy.ops.object.origin_set(type='ORIGIN_CURSOR', center='MEDIAN')
    head.location.z = 66
    
    return head

def create_shaft():
    """
    Create the metal shaft.
    
    Handle diameter: 5 cm (radius 2.5 cm)
    Shaft length: 118 cm
    Position: Z = -21 to +47 (68 cm visible portion)
    """
    bpy.ops.mesh.primitive_cylinder_add(radius=2.5, depth=68, segments=16)
    shaft = bpy.context.active_object
    shaft.name = "Shaft_Blockout"
    shaft.location.z = 13  # center of visible shaft portion
    
    return shaft

def create_pommel():
    """
    Create the faceted pommel/counterweight.
    
    Length: 18 cm
    Max width: 11 cm (radius ~5.5 cm)
    Position: Z = -103 to -85
    """
    bpy.ops.mesh.primitive_uv_sphere_add(
        radius=5.5,
        segments=6,
        ring_count=4
    )
    pommel = bpy.context.active_object
    pommel.name = "Pommel_Blockout"
    pommel.scale = (5.5, 5.5, 9)  # elongated along Z
    pommel.location.z = -94  # center of pommel
    
    return pommel

def create_grip_wrap():
    """
    Create the leather grip wrap zone indicator.
    
    Length: 42 cm along shaft
    Position: Z = -85 to -43
    """
    grip_start = -85
    grip_end = -43
    grip_length = grip_end - grip_start
    
    bpy.ops.mesh.primitive_cylinder_add(
        radius=3.5,  # slightly larger than shaft for wrap thickness
        depth=grip_length,
        segments=16
    )
    grip = bpy.context.active_object
    grip.name = "GripWrap_Blockout"
    grip.location.z = grip_start + (grip_length / 2)
    
    return grip

def create_rune_markers():
    """
    Create small emissive markers for rune inlay positions.
    These are placeholder locations for the emissive material zones.
    """
    rune_positions = [
        (27, 0, 70),   # rune on head face
        (-27, 0, 70),  # rune on head opposite
        (0, 3, 50),    # rune on shaft
        (0, -3, 50),   # rune on shaft opposite
    ]
    
    markers = []
    for i, pos in enumerate(rune_positions):
        bpy.ops.mesh.primitive_cube_add(size=2)
        rune = bpy.context.active_object
        rune.name = f"RuneMarker_{i}"
        rune.location = pos
        markers.append(rune)
    
    return markers

def assemble_blockout():
    """Create all components and return list."""
    components = []
    
    # Create materials
    mat_stone = create_material("Stone_Blockout", (0.2, 0.2, 0.25, 1.0))
    mat_metal = create_material("Metal_Blockout", (0.4, 0.35, 0.3, 1.0))
    mat_leather = create_material("Leather_Blockout", (0.3, 0.2, 0.15, 1.0))
    mat_rune = create_material("Rune_Blockout", (0.1, 0.5, 0.8, 1.0))
    
    # Create head
    head = create_head()
    head.data.materials.append(mat_stone)
    components.append(head)
    
    # Create shaft
    shaft = create_shaft()
    shaft.data.materials.append(mat_metal)
    components.append(shaft)
    
    # Create pommel
    pommel = create_pommel()
    pommel.data.materials.append(mat_metal)
    components.append(pommel)
    
    # Create grip wrap indicator
    grip = create_grip_wrap()
    grip.data.materials.append(mat_leather)
    components.append(grip)
    
    # Create rune markers
    runemarkers = create_rune_markers()
    for rm in runemarkers:
        rm.data.materials.append(mat_rune)
        components.append(rm)
    
    return components

if __name__ == "__main__":
    # Clear existing objects
    bpy.ops.wm.redraw_timer(type='DRAWBOX', new='EMPTY')
    
    # Create blockout
    components = assemble_blockout()
    
    # Print summary
    print(f"Created {len(components)} blockout components:")
    for comp in components:
        print(f"  - {comp.name}: {comp.location}")
    
    print("\nBlockout complete. Verify dimensions in viewport:")
    print("  Head: 52x38x32 cm centered at Z=66")
    print("  Shaft: 5cm diameter, 68cm length at Z=13")
    print("  Pommel: 11cm diameter, 18cm length at Z=-94")
    print("  Grip: 42cm wrap zone from Z=-85 to Z=-43")
    print("  Total span: 170 cm")
