#!/usr/bin/env python3
"""Build a contact sheet for Blood Axe cairn variant DCC proof renders.

Run with:
    python3 Tools/DCC/build_bloodaxe_cairn_variant_review_sheet.py

This reads the local proof renders generated by
`build_bloodaxe_cairn_variant_batch.py` and writes a compact review sheet to
both Saved/Automation and the tracked kit documentation folder.
"""

from __future__ import annotations

from pathlib import Path
from textwrap import wrap

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[2]
REVIEW_ROOT = ROOT / "Saved" / "Automation" / "DCC" / "BloodAxeCairnVariants_A01"
DOC_ROOT = ROOT / "docs" / "assets" / "kits" / "KIT_GIA_BloodAxeCairnVariantBatch_A01"

ASSETS = (
    ("SM_GIA_BloodAxeApproachCairnMarker_A01", "Approach Cairn Marker"),
    ("SM_GIA_BloodAxeRitualCairnGuidepost_A01", "Ritual Cairn Guidepost"),
    ("SM_GIA_BloodAxeLowThresholdCairn_A01", "Low Threshold Cairn"),
    ("SM_GIA_BloodAxeCollapsedThresholdCairn_A01", "Collapsed Threshold Cairn"),
    ("SM_GIA_BloodAxeCaveRemnantCairn_A01", "Cave Remnant Cairn"),
    ("SM_GIA_BloodAxeCollapsedCaveRemnantCairn_A01", "Collapsed Cave Remnant"),
    ("SM_GIA_BloodAxeCaveThresholdCairnPair_A01", "Cave Threshold Pair"),
    ("SM_GIA_BloodAxeMovedCampCairnPair_A01", "Moved-Camp Cairn Pair"),
    ("SM_GIA_BloodAxePairedCairnClosePair_A01", "Close Paired Cairns"),
    ("SM_GIA_BloodAxePairedCairnStaggeredPair_A01", "Staggered Paired Cairns"),
    ("SM_GIA_BloodAxeCairnPathMarker_A01", "Cairn Path Marker"),
    ("SM_GIA_BloodAxeCairnScrapCap_A01", "Cairn Scrap-Cap"),
)


def load_font(size: int) -> ImageFont.ImageFont:
    for candidate in (
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
    ):
        try:
            return ImageFont.truetype(candidate, size)
        except OSError:
            pass
    return ImageFont.load_default()


def proof_path(asset_name: str) -> Path:
    return REVIEW_ROOT / asset_name / f"{asset_name}_DCCReview.png"


def fit_image(image: Image.Image, size: tuple[int, int]) -> Image.Image:
    image = image.convert("RGB")
    resample = getattr(getattr(Image, "Resampling", Image), "LANCZOS")
    image.thumbnail(size, resample)
    canvas = Image.new("RGB", size, (37, 37, 34))
    x = (size[0] - image.width) // 2
    y = (size[1] - image.height) // 2
    canvas.paste(image, (x, y))
    return canvas


def draw_label(draw: ImageDraw.ImageDraw, text: str, xy: tuple[int, int], font: ImageFont.ImageFont) -> None:
    x, y = xy
    for line in wrap(text, width=34):
        draw.text((x, y), line, fill=(235, 230, 212), font=font)
        y += 18


def build_sheet() -> Image.Image:
    title_font = load_font(30)
    label_font = load_font(14)
    meta_font = load_font(13)

    columns = 3
    thumb_size = (520, 346)
    label_height = 54
    margin = 28
    gutter = 20
    header_height = 100
    rows = (len(ASSETS) + columns - 1) // columns

    sheet_width = margin * 2 + columns * thumb_size[0] + (columns - 1) * gutter
    cell_height = thumb_size[1] + label_height
    sheet_height = margin * 2 + header_height + rows * cell_height + (rows - 1) * gutter
    sheet = Image.new("RGB", (sheet_width, sheet_height), (24, 24, 22))
    draw = ImageDraw.Draw(sheet)

    draw.text((margin, margin), "Blood Axe Cairn Variant Batch A01 - DCC Game-Ready Candidate Review", fill=(242, 236, 216), font=title_font)
    draw.text(
        (margin, margin + 42),
        "Local proof renders only; not Unreal-imported, not final visual approval, not Fully game-ready.",
        fill=(190, 184, 166),
        font=meta_font,
    )

    for index, (asset_name, display_name) in enumerate(ASSETS):
        row = index // columns
        col = index % columns
        x = margin + col * (thumb_size[0] + gutter)
        y = margin + header_height + row * (cell_height + gutter)
        source = proof_path(asset_name)
        if source.exists():
            thumb = fit_image(Image.open(source), thumb_size)
        else:
            thumb = Image.new("RGB", thumb_size, (75, 28, 28))
            ImageDraw.Draw(thumb).text((18, 18), f"Missing proof render\n{asset_name}", fill=(255, 230, 220), font=label_font)

        sheet.paste(thumb, (x, y))
        draw.rectangle((x, y, x + thumb_size[0] - 1, y + thumb_size[1] - 1), outline=(96, 89, 72), width=1)
        draw.rectangle((x, y + thumb_size[1], x + thumb_size[0] - 1, y + thumb_size[1] + label_height - 1), fill=(34, 34, 31))
        draw_label(draw, f"{index + 1:02d}. {display_name}", (x + 12, y + thumb_size[1] + 9), label_font)

    return sheet


def main() -> None:
    sheet = build_sheet()
    saved_path = REVIEW_ROOT / "BloodAxeCairnVariants_A01_DCCReviewContactSheet.png"
    doc_path = DOC_ROOT / "BloodAxeCairnVariants_A01_DCCReviewContactSheet.png"
    saved_path.parent.mkdir(parents=True, exist_ok=True)
    doc_path.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(saved_path)
    sheet.save(doc_path)
    print(f"Wrote {saved_path.relative_to(ROOT)}")
    print(f"Wrote {doc_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
