#!/usr/bin/env python3
"""Build the illustrated Aerathea race size chart candidate.

The exact A04 scale authority is still generated by build_race_size_chart.py.
This script rebuilds the illustrated presentation composite from the clean v5
base:

- Replace the incorrect humanoid/Anubisath-like Basari figures with clean
  feline Basari alpha cutouts generated from the approved source language.
- Replace the clean-shaven male dwarf with a clean bearded dwarf alpha cutout.
- Preserve the clean v5 Giant and Minotaur figures unchanged.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter


ROOT = Path(__file__).resolve().parents[2]
REF_DIR = ROOT / "docs/assets/reference"
CONCEPT_DIR = Path("/home/Flamestrike/Desktop/Aerathea/Aerathea Creative/ASSET CONCEPTS")
BASARI_ALPHA = REF_DIR / "source/AET_Basari_SizeChart_Cutouts_Alpha_v1.png"
DWARF_MALE_ALPHA = REF_DIR / "source/AET_DwarfMale_SizeChart_Cutout_Alpha_v1.png"

OUT = REF_DIR / "AET_Race_Size_Comparison_A04_GameReady_v7.png"
OUT_HIGH = REF_DIR / "AET_Race_Size_Comparison_A04_GameReady_v7_HighRes.png"

BASELINE_Y = 1120
TOP_Y = 120
PX_PER_FOOT = (BASELINE_Y - TOP_Y) / 16.0
CHART_BG = (228, 220, 204, 255)
GRID = (176, 167, 153, 255)
INK = (43, 37, 31, 255)
TEXT = (33, 29, 24, 255)


@dataclass(frozen=True)
class RangeMark:
    center_x: float
    line_x: float
    min_ft: float
    max_ft: float
    label: str


RANGE_MARKS = [
    RangeMark(870, 893.436, 4 + 4 / 12, 5, '4\'4"-5\''),
    RangeMark(2425, 2443.3024, 6, 7, "6-7'"),
    RangeMark(2610, 2630.5344, 7, 8, "7-8'"),
]


def scaled_box(box: tuple[int, int, int, int], scale: int) -> tuple[int, int, int, int]:
    return tuple(int(v * scale) for v in box)  # type: ignore[return-value]


def y_for_ft(value: float, scale: int) -> int:
    return int(round((BASELINE_Y - value * PX_PER_FOOT) * scale))


def draw_dashed_hline(draw: ImageDraw.ImageDraw, x0: int, x1: int, y: int, scale: int) -> None:
    dash = 8 * scale
    gap = 8 * scale
    x = x0
    while x < x1:
        draw.line([(x, y), (min(x + dash, x1), y)], fill=GRID, width=max(1, scale))
        x += dash + gap


def restore_plot_background(img: Image.Image, box: tuple[int, int, int, int], scale: int) -> None:
    draw = ImageDraw.Draw(img)
    draw.rectangle(box, fill=CHART_BG)

    x0, y0, x1, y1 = box
    for foot in range(17):
        y = y_for_ft(foot, scale)
        if y0 <= y <= y1:
            draw_dashed_hline(draw, max(x0, 88 * scale), min(x1, 4160 * scale), y, scale)

    baseline = BASELINE_Y * scale
    if y0 <= baseline <= y1:
        draw.line(
            [(max(x0, 88 * scale), baseline), (min(x1, 4160 * scale), baseline)],
            fill=INK,
            width=3 * scale,
        )


def draw_range(draw: ImageDraw.ImageDraw, mark: RangeMark, scale: int) -> None:
    cx = int(round(mark.center_x * scale))
    lx = int(round(mark.line_x * scale))
    y_max = y_for_ft(mark.max_ft, scale)
    y_min = y_for_ft(mark.min_ft, scale)
    cap = 10 * scale
    width = max(2, 2 * scale)

    draw.line([(lx, y_max), (lx, y_min)], fill=TEXT, width=width)
    draw.line([(lx - cap, y_max), (lx + cap, y_max)], fill=TEXT, width=width)
    draw.line([(lx - cap, y_min), (lx + cap, y_min)], fill=TEXT, width=width)

    font = serif_font(30 * scale)
    draw.text((cx, y_max - 18 * scale), mark.label, fill=TEXT, font=font, anchor="mm")


def serif_font(size: int):
    font_paths = [
        "DejaVuSerif.ttf",
        "/usr/share/fonts/google-noto/NotoSerif-Regular.ttf",
        "/usr/share/fonts/liberation/LiberationSerif-Regular.ttf",
    ]
    try:
        from PIL import ImageFont

        for font_path in font_paths:
            try:
                return ImageFont.truetype(font_path, size)
            except Exception:
                continue
    except Exception:
        pass
    return None


def draw_footer(img: Image.Image, scale: int) -> None:
    draw = ImageDraw.Draw(img)
    y0 = 1386 * scale
    draw.rectangle((0, y0, img.width, img.height), fill=CHART_BG)
    footer = (
        "Illustrated v7 presentation layout generated from A04 race scale data "
        "with clean Basari and dwarf alpha cutouts, preserved Valar, Minotaur, and Giant source art."
    )
    draw.text(
        (img.width // 2, 1430 * scale),
        footer,
        fill=(71, 63, 52, 255),
        font=serif_font(22 * scale),
        anchor="mm",
    )


def concept_polygon_cutout(
    source: Path,
    points: list[tuple[int, int]],
    target_height: int,
) -> Image.Image:
    return concept_polygons_cutout(source, [points], target_height)


def concept_polygons_cutout(
    source: Path,
    polygons: list[list[tuple[int, int]]],
    target_height: int,
) -> Image.Image:
    src = Image.open(source).convert("RGBA")
    mask = Image.new("L", src.size, 0)
    draw = ImageDraw.Draw(mask)
    for points in polygons:
        draw.polygon(points, fill=255)
    mask = mask.filter(ImageFilter.GaussianBlur(1.1))

    bbox = mask.getbbox()
    if bbox is None:
        raise RuntimeError(f"Empty mask for {source}")

    cutout = src.crop(bbox)
    cutout.putalpha(mask.crop(bbox))
    scale = target_height / cutout.height
    target_width = max(1, int(round(cutout.width * scale)))
    return cutout.resize((target_width, target_height), Image.Resampling.LANCZOS)


def concept_mask_cutout(
    source: Path,
    include_polygons: list[list[tuple[int, int]]],
    exclude_polygons: list[list[tuple[int, int]]],
    target_height: int,
) -> Image.Image:
    src = Image.open(source).convert("RGBA")
    mask = Image.new("L", src.size, 0)
    draw = ImageDraw.Draw(mask)
    for points in include_polygons:
        draw.polygon(points, fill=255)
    for points in exclude_polygons:
        draw.polygon(points, fill=0)
    mask = mask.filter(ImageFilter.GaussianBlur(0.7))

    bbox = mask.getbbox()
    if bbox is None:
        raise RuntimeError(f"Empty mask for {source}")

    cutout = src.crop(bbox)
    cutout.putalpha(mask.crop(bbox))
    scale = target_height / cutout.height
    target_width = max(1, int(round(cutout.width * scale)))
    return cutout.resize((target_width, target_height), Image.Resampling.LANCZOS)


def chart_polygon_cutout(
    img: Image.Image,
    crop_box: tuple[int, int, int, int],
    points: list[tuple[int, int]],
    scale: int,
) -> Image.Image:
    crop = img.crop(crop_box).convert("RGBA")
    mask = Image.new("L", crop.size, 0)
    draw = ImageDraw.Draw(mask)
    scaled_points = [(int(x * scale), int(y * scale)) for x, y in points]
    draw.polygon(scaled_points, fill=255)

    pixels = crop.load()
    alpha = mask.load()
    bg = CHART_BG[:3]
    grid = GRID[:3]
    for y in range(crop.height):
        for x in range(crop.width):
            if alpha[x, y] == 0:
                continue
            r, g, b, _ = pixels[x, y]
            bg_dist = sum((value - target) ** 2 for value, target in zip((r, g, b), bg)) ** 0.5
            grid_dist = sum((value - target) ** 2 for value, target in zip((r, g, b), grid)) ** 0.5
            if bg_dist < 34 or grid_dist < 30:
                alpha[x, y] = 0

    mask = mask.filter(ImageFilter.GaussianBlur(0.7 * scale))
    bbox = mask.getbbox()
    if bbox is None:
        raise RuntimeError("Empty chart cutout")

    cutout = crop.crop(bbox)
    cutout.putalpha(mask.crop(bbox))
    return cutout


def paste_centered_bottom(
    img: Image.Image,
    cutout: Image.Image,
    center_x: int,
    bottom_y: int,
    x_offset: int = 0,
) -> tuple[int, int]:
    x = int(round(center_x - cutout.width / 2 + x_offset))
    y = int(round(bottom_y - cutout.height))
    img.alpha_composite(cutout, (x, y))
    return x, y


def paste_at(img: Image.Image, cutout: Image.Image, x: int, y: int) -> None:
    img.alpha_composite(cutout, (x, y))


def crop_alpha_bbox(img: Image.Image) -> Image.Image:
    alpha = img.getchannel("A")
    bbox = alpha.getbbox()
    if bbox is None:
        raise RuntimeError("Cutout has no non-transparent pixels")
    return img.crop(bbox)


def resize_to_height(img: Image.Image, target_height: int) -> Image.Image:
    scale = target_height / img.height
    target_width = max(1, int(round(img.width * scale)))
    return img.resize((target_width, target_height), Image.Resampling.LANCZOS)


def add_tail(draw: ImageDraw.ImageDraw, points: list[tuple[int, int]], scale: int) -> None:
    s = scale
    scaled = [(x * s, y * s) for x, y in points]
    draw.line(scaled, fill=(143, 92, 42, 230), width=13 * s, joint="curve")
    draw.line(scaled, fill=(220, 174, 91, 230), width=7 * s, joint="curve")
    for x, y in scaled[1::2]:
        draw.ellipse((x - 5 * s, y - 4 * s, x + 5 * s, y + 4 * s), fill=(58, 39, 25, 210))


def add_spots(draw: ImageDraw.ImageDraw, center_x: int, y_values: list[int], scale: int) -> None:
    s = scale
    offsets = [-26, -12, 10, 24, -18, 18, -6, 8]
    for index, y in enumerate(y_values):
        x = center_x + offsets[index % len(offsets)] * s
        ry = (3 + index % 3) * s
        rx = (2 + (index + 1) % 3) * s
        draw.ellipse((x - rx, y * s - ry, x + rx, y * s + ry), fill=(55, 36, 22, 145))


def add_basari_features(img: Image.Image, scale: int) -> None:
    sheet = Image.open(BASARI_ALPHA).convert("RGBA")
    female = crop_alpha_bbox(sheet.crop((0, 0, sheet.width // 2, sheet.height)))
    male = crop_alpha_bbox(sheet.crop((sheet.width // 2, 0, sheet.width, sheet.height)))
    female = resize_to_height(female, int(round((7 * PX_PER_FOOT) * scale)))
    male = resize_to_height(male, int(round((8 * PX_PER_FOOT) * scale)))
    paste_centered_bottom(img, female, 2425 * scale, BASELINE_Y * scale)
    paste_centered_bottom(img, male, 2610 * scale, BASELINE_Y * scale)


def add_dwarf_male_feature(img: Image.Image, scale: int) -> None:
    dwarf = crop_alpha_bbox(Image.open(DWARF_MALE_ALPHA).convert("RGBA"))
    dwarf = resize_to_height(dwarf, int(round((5 * PX_PER_FOOT) * scale)))
    paste_centered_bottom(img, dwarf, 870 * scale, BASELINE_Y * scale)


def patch_chart(base_path: Path, out_path: Path, scale: int) -> None:
    base = Image.open(base_path).convert("RGBA")

    restore_plot_background(base, scaled_box((790, 725, 985, 1124), scale), scale)
    restore_plot_background(base, scaled_box((2328, 525, 2735, 1124), scale), scale)

    add_dwarf_male_feature(base, scale)
    add_basari_features(base, scale)

    draw = ImageDraw.Draw(base)
    for mark in RANGE_MARKS:
        draw_range(draw, mark, scale)
    draw_footer(base, scale)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    base.save(out_path)


def main() -> None:
    patch_chart(REF_DIR / "AET_Race_Size_Comparison_A04_GameReady_v5.png", OUT, 1)
    patch_chart(REF_DIR / "AET_Race_Size_Comparison_A04_GameReady_v5_HighRes.png", OUT_HIGH, 2)


if __name__ == "__main__":
    main()
